# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.11
_src_path: https://github.com/algorandfoundation/algokit-fullstack-template
author_email: 150678985+FlamoDynamo@users.noreply.github.com
author_name: FlamoDynamo
cloud_provider: vercel
contract_name: contract
deployment_language: python
preset_name: production
project_name: UTC2-AlgoLib

