# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.7
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: 150678985+FlamoDynamo@users.noreply.github.com
author_name: FlamoDynamo
cloud_provider: vercel
preset_name: production
project_name: UTC2-AlgoLib-frontend

